### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by unfa** [nimbletools/misstortion#2]
Since Misstortion is based on JUCE - would it be possible to build an LV2 version (for easy use in Linux-friendly hosts like Ardour, Carla etc?).

**Comment by codecat** [comment]
Probably! I'll take a look.

**Comment by pdesaulniers** [comment]
I've managed to build Misstortion as an LV2 using [falkTX's fork of JUCE](https://github.com/DISTRHO/juce). I you want, I can clean that up and send a pull request soon :) 

It involves adding the JuceLibraryCode folder to the repo, the fork of JUCE, some LV2-specific stuff to the AppConfig.h file, and some premake script that I adapted from [another project](https://github.com/mzuther/K-Meter/blob/master/Builds/premake5.lua). I suppose the Makefile generated by premake can be used directly too.

But then, I've also thought of making a repo that contains JUCE plugins ports to LV2, just like the [DISTRHO-Ports](https://github.com/DISTRHO/DISTRHO-Ports). Maybe I should just add Misstortion there instead? I guess it could be nice to bundle Misstortion with other plugins and distribute it that way. Also, this might be a good approach if you don't want to deal with Linux support too much.

**Comment by codecat** [comment]
That's great! What exactly is required to get Misstortion to build with that fork?

I'd prefer not to have any of JUCE's sources in the repo, to keep the repository clean and consistent. Isn't it possible to just use a different set of JUCE sources from Projucer? Or do you need to actually change the source of the plugin too?

That DISTRHO repository looks interesting, although it looks like those are typically added as regular files rather than as git submodules. Maybe adding the plugin source as a submodule would be more beneficial? (Depending on how much has to change, of course.)

Also, referencing this issue here too; https://github.com/WeAreROLI/JUCE/issues/123

**Comment by pdesaulniers** [comment]
LV2 support in JUCE has been pending since about 2012, so I suppose it's reasonable to use the fork for now :p

As for what is required, I'll send a pull request that shows that. It's in my fork right now, but I want to test it on a different computer first: https://github.com/pdesaulniers/misstortion

There is no need to change the source code itself. However, I needed to remove the juce_video and juce_opengl modules from the .jucer project for some reason. I hope they weren't used on other platforms :p

**Comment by codecat** [comment]
I'll close this for now, you should check out pdesaulniers' fork for the LV2 version! Also see #3 for prebuilt binaries. (Perhaps you should add the prebuilt binaries to the releases page on your fork?)

**Comment by pdesaulniers** [comment]
Yep! I've added a Linux VST build as well, cause why not :)
